resources:
  - name: gitresource
    type: GitRepo
    configuration:
      gitProvider: github
      path: vijayreddy1991/dummy
      files:  # optional
        include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master 
        exclude: readme
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: false
      shallowDepth: 10  # optional 
      
pipelines:

  - name: pipelines_auto
    steps:
      - name: s_Bash
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: github
          inputResources:
            - name: gitresource
        execution:
          onStart:
             - echo "Preparing for work..."
          onExecute:
            - printenv
            - printenv
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"  
