resources:
  - name: gitresource
    type: GitRepo
    configuration:
      gitProvider: git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master 
        exclude: readme
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: false
      shallowDepth: 10  # optional 

  - name: gitres
    type: GitRepo
    configuration:
      gitProvider: git
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master 
        exclude: readme
      buildOn:  # optional
         commit: false
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: false
      shallowDepth: 10  # optional 

pipelines:

  - name: pipelines_true
    steps:
      - name: s_BashTriggerTrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: git
          inputResources:
            - name: gitresource
        execution:
          onExecute:
            - printenv 

pipelines:

  - name: pipelines_False

      - name: s_BashTriggerFalse
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: git
          inputResources:
            - name: gitres
        execution:              
          onExecute:
            - printenv

