resources:
  - name: gitresource
    type: GitRepo
    configuration:
      gitProvider: git
      path: vijayreddy1991/dummy
#       files:  # optional
# #         include: pipelines.sh
#         exclude: readme
#       branches:  # optional
#         include: master 
#         exclude: readme
#       buildOn:  # optional
#          commit: true
#          pullRequestCreate: true
#          pullRequestClose: true
#          releaseCreate: true
#          tagCreate: false
#       shallowDepth: 10  # optional 


pipelines:

  - name: pipelines_auto
    steps:
      - name: s_BashTriggerTrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: git
          inputResources:
            - name: gitresource
              trigger: true
        execution:
          onExecute:
            - printenv 

      - name: s_BashTriggerFalse
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: git
          inputResources:
            - name: gitresource
              trigger: false
        execution:              
          onExecute:
            - printenv

